services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.rails.dev
    environment:
      - RAILS_MASTER_KEY
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: progress_tracker_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d progress_tracker_development"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: